language: groovy
jdk:
- openjdk7
before_script:
- rm -rf target
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: JaFy58AdmU5xBKcUhdcDAQpG9cKbSsNjuVIN/JVuRKUiF+ybVpUEIwSMrsD4twi60zmMOrTevWuDc0u+euxfO0PV9z1/c/KeMLqJqY/vYgRaGZqo+hbL/gNjfoJNRhpxCpQyx1eL0Z06VxFmF6lU7zS/eeJ3fn8wrKtUl5gGD0Q=
  - secure: PGe50WPj2amLzvPHXQNsEIUqDbVQAwTnF7isrGdpAu7iioF2JEUyKMiAM9sNBWBnNyd1iUHgvrRvU0n/7JDJq52g3cxIH++sW7M5kVWbqDg0zo1aJmTWf9yf2t0Z8dkh9JHp1bTawrleKZGeJEOChS+OmHvS7Hk9iPpN13TFAOc=
  - secure: WzglbKCji6ggEWmX5xKX0ufQ9ANIPX9tOg++u5vHnEUC1NSHBwbVyfVNfrcM/n/vIzz7huahZOtYx6ec77tNo7a388/MdNZ2lrOfdJhuAX9yx9KoVJHdvJ5zG4hFiuQ0Z/yuIV0x2kiMgmIP6cO4Lg/rWC39frAm26m0efCKJCg=
